name: Release Build

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for release (e.g. v1.0.0)"
        required: true
        default: "v1.0.0"

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Update version
        shell: bash
        run: |
          VERSION="${{ inputs.tag_name }}"
          if [[ $VERSION == v* ]]; then
            VERSION="${VERSION:1}"
          fi
          npm version $VERSION --no-git-tag-version --allow-same-version

      - name: Build and Publish
        run: |
          npm run build
          npx electron-builder --mac --publish=always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}